// Generated by safari-web-extension-converter (iOS-only target)

import UIKit
import SafariServices

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .systemBackground
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        // Show Safari settings for the extension on first launch
        SFSafariApplication.showPreferencesForExtension(withIdentifier: "com.ai-dict.safari.Extension") { error in
            DispatchQueue.main.async {
                if let error {
                    print("Error opening Safari preferences: \(error)")
                } else {
                    self.dismiss(animated: true)
                }
            }
        }
    }
}
