#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIST="$ROOT/dist"
# Generated by safari-web-extension-converter; confirm the leaf name in the committed project.
RES="$ROOT/xcode/AI Dictionary Extension/Resources"
[ -d "$DIST" ] || { echo "build dist/ first: pnpm --filter @ai-dict/extension-safari build"; exit 1; }
rm -rf "$RES"
mkdir -p "$RES"
cp -R "$DIST"/. "$RES"/
echo "synced dist/ → $RES"
