// ---------------------------------------------------------------------------
// lite-wire-schema.ts — SIZE-BUDGET SHIM for the SW bundle
//
// This module is the source that esbuild bundles into dist/sw.js in place of
// @ai-dict/core's wire-schema.ts (which imports zod, ~250 KB).  The shim keeps
// the SW bundle within the §8.7 size budget by implementing only what the
// service worker actually needs: a type-discriminant check + field-stripping.
//
// CONTRACT (must stay shape-compatible with @ai-dict/core's WireMessage union):
//   Valid types: 'lookup' | 'lookup.cancel' | 'settings.get' | 'history.list'
//                | 'history.clear' | 'cache.clear' | 'connection.test'
//   'lookup' additionally requires req to be a non-null object with string `word`.
//
// On success, safeParse returns ONLY the whitelisted fields for that variant
// (field-stripping) — unknown extra fields are silently dropped so that nothing
// the router doesn't expect can reach it.
//
// The CANONICAL validator (zod WireMessageSchema) lives in @ai-dict/core and is
// exercised by vitest unit tests + the bundle-07 wire:check script.  Do NOT rely
// on this shim for validation in any context other than the SW browser bundle.
//
// NO dependencies on zod or any other library — must remain zero-import.
// ---------------------------------------------------------------------------

const VALID_TYPES = new Set([
  'lookup',
  'lookup.cancel',
  'settings.get',
  'history.list',
  'history.clear',
  'cache.clear',
  'connection.test',
] as const);

type ValidType = typeof VALID_TYPES extends Set<infer T> ? T : never;

// Whitelisted-field shapes returned by safeParse on success.
// These mirror the WireMessage discriminated union in @ai-dict/core exactly.
// req is reconstructed from whitelisted fields only — no index signature so no extra fields survive.
type StrippedLookup = { type: 'lookup'; req: { word: string; context?: unknown }; requestId?: unknown };
type StrippedLookupCancel = { type: 'lookup.cancel'; requestId?: unknown };
type StrippedHistoryList = { type: 'history.list'; limit?: unknown; cursor?: unknown };
type StrippedSimple = { type: 'settings.get' | 'history.clear' | 'cache.clear' | 'connection.test' };

type StrippedMessage = StrippedLookup | StrippedLookupCancel | StrippedHistoryList | StrippedSimple;

function isNonNullObject(v: unknown): v is Record<string, unknown> {
  return v !== null && typeof v === 'object';
}

export const WireMessageSchema = {
  safeParse(m: unknown): { success: false } | { success: true; data: StrippedMessage } {
    if (!isNonNullObject(m)) return { success: false };
    if (!VALID_TYPES.has(m['type'] as ValidType)) return { success: false };

    const type = m['type'] as ValidType;

    if (type === 'lookup') {
      const req = m['req'];
      if (!isNonNullObject(req) || typeof req['word'] !== 'string') return { success: false };
      // Reconstruct req from whitelisted fields only — unknown extra fields are silently dropped.
      const strippedReq: { word: string; context?: unknown } = { word: req['word'] };
      if ('context' in req) strippedReq.context = req['context'];
      const stripped: StrippedLookup = { type: 'lookup', req: strippedReq };
      if ('requestId' in m) stripped.requestId = m['requestId'];
      return { success: true, data: stripped };
    }

    if (type === 'lookup.cancel') {
      const stripped: StrippedLookupCancel = { type: 'lookup.cancel' };
      if ('requestId' in m) stripped.requestId = m['requestId'];
      return { success: true, data: stripped };
    }

    if (type === 'history.list') {
      const stripped: StrippedHistoryList = { type: 'history.list' };
      if ('limit' in m) stripped.limit = m['limit'];
      if ('cursor' in m) stripped.cursor = m['cursor'];
      return { success: true, data: stripped };
    }

    // settings.get | history.clear | cache.clear | connection.test — no payload
    const simpleStripped: StrippedSimple = { type };
    return { success: true, data: simpleStripped };
  },
};

// Returns an empty JSON schema stub — the real schema is generated by core's
// wireJsonSchema() using zod.toJSONSchema().  The SW bundle never needs it.
export function wireJsonSchema(): Record<string, never> {
  return {};
}
